name: databreeze_sqlite
description: "Implementation of a SQLite backend for DataBreeze."
version: 1.0.0-alpha.1
# homepage:
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  databreeze:

  meta: ^1.16.0
  # collection: ^1.19.1
  path: ^1.9.1
  path_provider: ^2.1.5
  logging: ^1.3.0
  sqlite_async: ^0.12.2
  sqlite3: ^2.9.3
  # sqlite3_flutter_libs: ^0.5.40

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
