name: databreeze_sqlite
description: "Implementation of a SQLite backend for DataBreeze."
version: 1.0.0-alpha.1
# homepage:
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  databreeze:

  meta: ^1.17.0
  # collection: ^1.19.1
  path: ^1.9.1
  logging: ^1.3.0
  sqlite_async: ^0.13.1
  sqlite3: ^2.9.4
  # sqlite3_flutter_libs: ^0.5.40

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
