name: databreeze_sqlite
description: "A new Flutter package project."
version: 0.0.1
# homepage:
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  databreeze: ^0.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
