name: databreeze
description: "A lightweight ORM version with support for various database backends and reactivity."
version: 0.0.1
# homepage:
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  meta: ^1.16.0
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  logging: ^1.3.0
