name: databreeze_flutter_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  databreeze:
  databreeze_sqlite:
  databreeze_flutter:
  sqlite3_flutter_libs: ^0.5.40
  sqlite_async: ^0.13.1
  provider: ^6.1.5+1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
