name: gen_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  databreeze:
  databreeze_annotation:
  build_runner: ^2.11.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
  databreeze_generator:
